'use client';

import { useState } from "react";
import { GithubUser, GithubRepo } from "@/types/github";
import { LanguageStat, TopicStat } from "@/lib/github";
import { ThemeName, THEMES } from "@/lib/themes";
import HeroSection from "@/components/HeroSection";
import ProjectsGrid from "@/components/ProjectsGrid";
import LanguageBar from "@/components/LanguageBar";
import TopicBar from "@/components/TopicBar";
import ThemeSwitcher from "@/components/themeswitcher";
import Link from "next/link";
import QRCodeSection from "@/components/QRCodeSection";

type Props = {
  user: GithubUser;
  topRepos: GithubRepo[];
  languageStats: LanguageStat[];
  topicStats: TopicStat[];
};

export default function PortfolioShell({
  user,
  topRepos,
  languageStats,
  topicStats,
}: Props) {
  const [theme, setTheme] = useState<ThemeName>("minimal");
  const t = THEMES[theme];
  function handleDownloadPDF() {
    // Let the QR canvas finish painting before opening the print dialog
    requestAnimationFrame(() => {
      setTimeout(() => window.print(), 200);
    });
  }

  return (
    <div className={`min-h-screen transition-colors duration-300 ${t.page}`}>
      {/* ── Top navbar ── */}
      <nav className={`sticky top-0 z-50 border-b ${t.border}
                       backdrop-blur-md bg-opacity-80 no-print`}
           style={{ backgroundColor: 'inherit' }}>
        <div className="max-w-4xl mx-auto px-4 h-14 flex items-center
                        justify-between gap-4">

          {/* Left — back to home */}
          <Link
            href="/"
            className={`text-sm font-semibold tracking-tight ${t.heading}
                        hover:opacity-70 transition-opacity`}
          >
            ← Portify
          </Link>

          {/* Right — theme switcher + PDF */}
          <div className="flex items-center gap-2">
            <ThemeSwitcher current={theme} onChange={setTheme} />

            <button
              onClick={handleDownloadPDF}
              className={`text-xs px-3 py-1.5 rounded-full border
                         ${t.border} ${t.body}
                         hover:opacity-80 transition-all duration-200
                         flex items-center gap-1.5`}
            >
              <span>↓</span>
              <span>PDF</span>
            </button>
          </div>

        </div>
      </nav>

      {/* ── Main content ── */}
      <main className="max-w-4xl mx-auto px-4 py-10" id="portfolio-content">
        <HeroSection user={user} theme={t} />
        <LanguageBar stats={languageStats} theme={t} />
        <TopicBar stats={topicStats} theme={t} />
        <ProjectsGrid repos={topRepos} theme={t} />
        <QRCodeSection username={user.login} />
      </main>

      {/* ── Footer ── */}
      <footer className={`border-t ${t.border} mt-16 py-6 no-print`}>
        <div className={`max-w-4xl mx-auto px-4 flex justify-between
                         items-center text-xs ${t.body}`}>
          <span>Generated by <strong>Portify</strong></span>
          <a
            href={user.html_url}
            target="_blank"
            rel="noopener noreferrer"
            className="hover:opacity-70 transition-opacity"
          >
            View on GitHub ↗
          </a>
        </div>
      </footer>

    </div>
  );
}