'use client';

import { useEffect, useState } from "react";
import { GithubUser, GithubRepo } from "@/types/github";
import { LanguageStat, TopicStat } from "@/lib/github";
import HeroSection from "@/components/HeroSection";
import ProjectsGrid from "@/components/ProjectsGrid";
import LanguageBar from "@/components/LanguageBar";
import TopicBar from "@/components/TopicBar";
import ThemeSwitcher from "@/components/home/ThemeSwitcher";
import Link from "next/link";
import QRCodeSection from "@/components/QRCodeSection";
import GithubIcon from "@/components/home/GithubIcon";
import { CONTAINER } from "@/components/home/layout";

type Props = {
  user: GithubUser;
  topRepos: GithubRepo[];
  languageStats: LanguageStat[];
  topicStats: TopicStat[];
};

export default function PortfolioShell({
  user,
  topRepos,
  languageStats,
  topicStats,
}: Props) {
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 12);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  function handleDownloadPDF() {
    requestAnimationFrame(() => {
      setTimeout(() => window.print(), 200);
    });
  }

  return (
  <>
      <header
        className={`sticky top-0 z-50 w-full transition-[background,box-shadow,border-color] duration-300 ease-out no-print ${
          scrolled ? "home-nav-glass" : "bg-[var(--home-bg)]/80 backdrop-blur-sm border-b border-[var(--home-border-subtle)]"
        }`}
      >
        <div className={`${CONTAINER} flex h-14 items-center justify-between gap-4`}>
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--home-text)] hover:text-[var(--home-primary)] transition-colors duration-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--home-primary)] rounded-lg py-1 shrink-0"
          >
            <GithubIcon className="h-5 w-5 shrink-0" />
            <span>Portify</span>
          </Link>

          <div className="flex items-center gap-2">
            <ThemeSwitcher compact />
            <button
              type="button"
              onClick={handleDownloadPDF}
              className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-[var(--home-border)] bg-[var(--home-surface)] px-3 text-xs font-medium text-[var(--home-muted)] hover:border-[var(--home-border-hover)] hover:text-[var(--home-text)] transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--home-primary)]"
            >
              <span aria-hidden>↓</span>
              PDF
            </button>
          </div>
        </div>
      </header>

      <main className={`${CONTAINER} py-10 sm:py-12 lg:py-14`} id="portfolio-content">
        <HeroSection user={user} />
        <LanguageBar stats={languageStats} />
        <TopicBar stats={topicStats} />
        <ProjectsGrid repos={topRepos} />
        <QRCodeSection username={user.login} />
      </main>

      <footer className="border-t border-[var(--home-border-subtle)] mt-8 py-8 no-print">
        <div className={`${CONTAINER} flex flex-col gap-3 sm:flex-row sm:justify-between sm:items-center text-xs text-[var(--home-subtle)]`}>
          <span>
            Generated by{" "}
            <Link href="/" className="home-link font-medium">
              Portify
            </Link>
          </span>
          <a
            href={user.html_url}
            target="_blank"
            rel="noopener noreferrer"
            className="home-link inline-flex items-center gap-1"
          >
            View on GitHub ↗
          </a>
        </div>
      </footer>
  </>
  );
}
