"use client";

import { getPortfolioUrl } from "@/lib/site";
import { QRCodeCanvas } from "qrcode.react";
import { useSyncExternalStore } from "react";

type Props = {
  username: string;
};

function subscribe() {
  return () => {};
}

export default function QRCodeSection({ username }: Props) {
  const portfolioUrl = useSyncExternalStore(
    subscribe,
    () => getPortfolioUrl(username),
    () => "",
  );

  if (!portfolioUrl) return null;

  const siteHost = new URL(portfolioUrl).host;

  return (
    <div className="qr-section">
      <div className="qr-section-inner">
        <div>
          <p className="qr-title">View live portfolio</p>
          <p className="qr-subtitle">Scan to open the interactive version</p>
          <p className="qr-url">{portfolioUrl}</p>
        </div>

        <div className="qr-code-wrap">
          <QRCodeCanvas
            value={portfolioUrl}
            size={96}
            bgColor="#ffffff"
            fgColor="#000000"
            level="H"
            includeMargin
          />
        </div>
      </div>

      <p className="qr-footer">Generated by Portify — {siteHost}</p>
    </div>
  );
}
