"use client";

import { getPortfolioUrl } from "@/lib/site";
import { QRCodeCanvas } from "qrcode.react";
import { useSyncExternalStore } from "react";

type Props = {
  username: string;
  compact?: boolean;
};

function subscribe() {
  return () => {};
}

export default function QrCodeCard({
  username,
  compact = false,
}: Props) {
  const portfolioUrl = useSyncExternalStore(
    subscribe,
    () => getPortfolioUrl(username),
    () => "",
  );

  if (!portfolioUrl) return null;

  const siteHost = new URL(portfolioUrl).host;
  const qrSize = compact ? 72 : 96;

  return (
    <div className="qr-section">
      <div
        className={`flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 sm:gap-6 ${
          compact ? "" : "home-card p-4 sm:p-5"
        }`}
      >
        <div className="min-w-0">
          <p className={`font-medium text-[var(--home-text)] ${compact ? "text-xs" : "text-sm"}`}>
            View live portfolio
          </p>
          <p className={`text-[var(--home-muted)] mt-1 ${compact ? "text-[10px] leading-snug" : "text-xs"}`}>
            Scan to open the interactive version
          </p>
          {!compact && (
            <p className="text-xs font-mono text-[var(--home-code-link)] mt-3 break-all">
              {portfolioUrl}
            </p>
          )}
          {compact && (
            <p className="text-[10px] font-mono text-[var(--home-subtle)] mt-2 truncate">
              portify /u/{username}
            </p>
          )}
        </div>

        <div className="qr-code-wrap shrink-0 self-start sm:self-center rounded-lg border border-[var(--home-border)] bg-white p-1.5 shadow-[var(--home-elevation-2)]">
          <QRCodeCanvas
            value={portfolioUrl}
            size={qrSize}
            bgColor="#ffffff"
            fgColor="#000000"
            level="H"
            includeMargin={false}
          />
        </div>
      </div>

      {!compact && (
        <p className="qr-footer text-xs text-[var(--home-subtle)] text-center mt-4">
          Generated by Portify — {siteHost}
        </p>
      )}
    </div>
  );
}
