"use client";

import { QRCodeSVG } from "qrcode.react";
import { useEffect, useState } from "react";

type Props = {
  username: string;
};

export default function QRCodeSection({ username }: Props) {
  const [portfolioUrl, setPortfolioUrl] = useState<string | null>(null);

  useEffect(() => {
    // Always use the URL the user is actually on — works on Vercel previews,
    // production, and custom domains without relying on env vars.
    setPortfolioUrl(`${window.location.origin}/u/${username}`);
  }, [username]);

  if (!portfolioUrl) return null;

  const siteHost = new URL(portfolioUrl).host;

  return (
    <div className="qr-section">
      <div
        style={{
          borderTop: "1px solid #e5e7eb",
          marginTop: "2rem",
          paddingTop: "1.5rem",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          gap: "1.5rem",
        }}
      >
        <div>
          <p
            style={{
              fontSize: "13px",
              fontWeight: 600,
              color: "#111",
              margin: "0 0 4px",
            }}
          >
            View live portfolio
          </p>
          <p
            style={{
              fontSize: "11px",
              color: "#6b7280",
              margin: "0 0 4px",
            }}
          >
            Scan to open the interactive version
          </p>
          <p
            style={{
              fontSize: "11px",
              color: "#6b7280",
              margin: 0,
              fontFamily: "monospace",
              wordBreak: "break-all",
            }}
          >
            {portfolioUrl}
          </p>
        </div>

        <div
          style={{
            padding: "8px",
            border: "1px solid #e5e7eb",
            borderRadius: "8px",
            background: "white",
            flexShrink: 0,
          }}
        >
          <QRCodeSVG
            value={portfolioUrl}
            size={90}
            bgColor="#ffffff"
            fgColor="#000000"
            level="M"
            includeMargin={false}
          />
        </div>
      </div>

      <p
        style={{
          fontSize: "10px",
          color: "#9ca3af",
          textAlign: "center",
          marginTop: "1rem",
        }}
      >
        Generated by Portify — {siteHost}
      </p>
    </div>
  );
}
