"use client";

import { QRCodeCanvas } from "qrcode.react";
import { useSyncExternalStore } from "react";

type Props = {
  username: string;
};

function subscribe() {
  return () => {};
}

function getOrigin() {
  return window.location.origin;
}

export default function QRCodeSection({ username }: Props) {
  const origin = useSyncExternalStore(subscribe, getOrigin, () => "");

  if (!origin) return null;

  const portfolioUrl = `${origin}/u/${username}`;
  const siteHost = new URL(portfolioUrl).host;

  return (
    <div className="qr-section">
      <div className="qr-section-inner">
        <div>
          <p className="qr-title">View live portfolio</p>
          <p className="qr-subtitle">Scan to open the interactive version</p>
          <p className="qr-url">{portfolioUrl}</p>
        </div>

        <div className="qr-code-wrap">
          <QRCodeCanvas
            value={portfolioUrl}
            size={96}
            bgColor="#ffffff"
            fgColor="#000000"
            level="H"
            includeMargin
          />
        </div>
      </div>

      <p className="qr-footer">Generated by Portify — {siteHost}</p>
    </div>
  );
}
